### ISSUE TITLE
make_check xversion disabled

### ISSUE THREAD

**Issue by jjhursey** [openpmix/pmix-tests#40]
In PR #38 the `make_check` variant of the cross-version script was disabled while a broader fix to the make check tests is undertaken. I want to file a ticket so we don't forget that this will silently skip testing and return success if enabled.

 * https://github.com/openpmix/pmix-tests/pull/38/files#diff-06bd1aa2d4ce8d219399f611e8523259R347-R348

**Comment by rhc54** [comment]
v2.0 is also turned off as it doesn't support non-dstore operations

**Comment by jjhursey** [comment]
I created https://github.com/openpmix/openpmix/issues/1515 to track the fix.

**Comment by jjhursey** [comment]
This unit test is running again so we can close this.
CI runs it as `IBM CI (Cross-version: make check)`
